const {createClient}=supabase;const sb=createClient(ML_CONFIG.SUPABASE_URL,ML_CONFIG.SUPABASE_PUBLISHABLE_KEY);const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));let members=[],editing=null;
async function init(){const {data:{session}}=await sb.auth.getSession();if(session) await openDash();else $("#login").classList.remove("hidden")}
async function openDash(){const {data:user}=await sb.auth.getUser();const {data:admin,error}=await sb.from("admin_users").select("user_id").eq("user_id",user.user.id).maybeSingle();if(error||!admin){await sb.auth.signOut();$("#loginMsg").textContent="Akun ini bukan admin.";return}$("#login").classList.add("hidden");$("#dash").classList.remove("hidden");await refresh()}
$("#loginBtn").onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginMsg").textContent=error.message;else openDash()};
$("#logout,#logout2").onclick=async e=>{e.preventDefault();await sb.auth.signOut();location.reload()};
async function refresh(){const [m,p,e,g]=await Promise.all([sb.from("members").select("*").order("generation").order("name"),sb.from("member_parents").select("*"),sb.from("events").select("*").order("sort_order"),sb.from("gallery").select("*").order("sort_order")]);if(m.error||p.error||e.error||g.error){alert("Gagal mengambil data. Cek RLS dan SQL.");return}members=m.data||[];window.parents=p.data||[];renderMembers();renderEvents(e.data||[]);renderGallery(g.data||[]);fillParents()}
function fillParents(selected=[]){$("#parents").innerHTML=members.map(m=>`<option value="${m.id}" ${selected.includes(m.id)?"selected":""}>${esc(m.name)}</option>`).join("")}
function renderMembers(){const parents=window.parents||[];$("#memberRows").innerHTML=members.map(m=>{const ps=parents.filter(p=>p.member_id===m.id).map(p=>members.find(x=>x.id===p.parent_id)?.name).filter(Boolean).join(", ")||"—";return `<div class="row"><b>${esc(m.name)}</b><span>${esc(m.rank)}</span><span>Gen. ${m.generation}</span><span>${esc(ps)}</span><span><button class="btn-admin secondary" onclick="editMember('${m.id}')">Edit</button> <button class="btn-admin danger" onclick="deleteMember('${m.id}')">Hapus</button></span></div>`}).join("")||"<p style='color:#999'>Belum ada anggota.</p>"}
window.editMember=async id=>{const m=members.find(x=>x.id===id);if(!m)return;editing=id;$("#memberTitle").textContent="Edit Anggota";$("#name").value=m.name;$("#rank").value=m.rank;$("#generation").value=m.generation;$("#status").value=m.status;$("#origin").value=m.origin;$("#relation").value=m.relation;$("#bio").value=m.bio;fillParents((window.parents||[]).filter(p=>p.member_id===id).map(p=>p.parent_id));$("#cancel").classList.remove("hidden");scrollTo({top:250,behavior:"smooth"})};
window.deleteMember=async id=>{const m=members.find(x=>x.id===id);if(!confirm(`Hapus ${m.name}?`))return;const {error}=await sb.from("members").delete().eq("id",id);if(error)alert(error.message);else refresh()};
$("#cancel").onclick=()=>{editing=null;$("#memberTitle").textContent="Tambah Anggota";$("#name").value="";$("#rank").value="";$("#generation").value=1;$("#status").value="Active";$("#origin").value="France";$("#relation").value="";$("#bio").value="";$("#photoFile").value="";fillParents();$("#cancel").classList.add("hidden")};
async function uploadPhoto(file){if(!file)return null;const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`members/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from("family-photos").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}
$("#saveMember").onclick=async()=>{
 const name=$("#name").value.trim(),rank=$("#rank").value.trim();if(!name||!rank){alert("Nama dan jabatan wajib.");return}
 try{
  let photoPath=null;if($("#photoFile").files[0])photoPath=await uploadPhoto($("#photoFile").files[0]);
  const payload={name,rank,generation:Number($("#generation").value)||1,status:$("#status").value.trim(),origin:$("#origin").value.trim(),relation:$("#relation").value.trim(),bio:$("#bio").value.trim()};if(photoPath)payload.photo_path=photoPath;
  let id=editing;
  if(editing){const {error}=await sb.from("members").update(payload).eq("id",editing);if(error)throw error;await sb.from("member_parents").delete().eq("member_id",editing)}
  else{const {data,error}=await sb.from("members").insert(payload).select("id").single();if(error)throw error;id=data.id}
  const ps=[...$("#parents").selectedOptions].map(o=>({member_id:id,parent_id:o.value}));if(ps.length){const {error}=await sb.from("member_parents").insert(ps);if(error)throw error}
  alert("Anggota tersimpan.");$("#cancel").click();await refresh();
 }catch(e){alert(e.message)}
};
function renderEvents(list){$("#events").innerHTML=list.map((e,i)=>`<div class="form-grid event-row" data-id="${e.id}" style="margin-bottom:15px"><div class="field"><label>Tahun</label><input class="ey" value="${esc(e.year)}"></div><div class="field"><label>Judul</label><input class="et" value="${esc(e.title)}"></div><div class="field full"><label>Cerita</label><textarea class="eb">${esc(e.body)}</textarea></div><button class="btn-admin danger remove-event">Hapus</button></div>`).join("")}
$("#addEvent").onclick=()=>{$("#events").insertAdjacentHTML("beforeend",`<div class="form-grid event-row new" style="margin-bottom:15px"><div class="field"><label>Tahun</label><input class="ey" value="2026"></div><div class="field"><label>Judul</label><input class="et" value=""></div><div class="field full"><label>Cerita</label><textarea class="eb"></textarea></div><button class="btn-admin danger remove-event">Hapus</button></div>`);bindRemove()};
function bindRemove(){document.querySelectorAll(".remove-event").forEach(b=>b.onclick=()=>b.parentElement.remove())}bindRemove();
$("#saveEvents").onclick=async()=>{try{const {data:old}=await sb.from("events").select("id");for(const id of (old||[]).map(x=>x.id))await sb.from("events").delete().eq("id",id);const rows=[...document.querySelectorAll(".event-row")];const payload=rows.map((r,i)=>({year:r.querySelector(".ey").value,title:r.querySelector(".et").value,body:r.querySelector(".eb").value,sort_order:i})).filter(x=>x.title);if(payload.length)await sb.from("events").insert(payload);alert("History tersimpan.");refresh()}catch(e){alert(e.message)}};
function renderGallery(list){$("#gallery").innerHTML=list.map(g=>`<div class="form-grid gallery-row" data-id="${g.id}" style="margin-bottom:15px"><div class="field"><label>Judul</label><input class="gt" value="${esc(g.title)}"></div><div class="field"><label>Gambar</label><input class="gf" type="file" accept="image/*"></div><div class="field"><label>Path saat ini</label><input class="gp" value="${esc(g.image_path)}"></div><button class="btn-admin danger remove-gallery">Hapus</button></div>`).join("")} 
$("#addGallery").onclick=()=>{$("#gallery").insertAdjacentHTML("beforeend",`<div class="form-grid gallery-row new" style="margin-bottom:15px"><div class="field"><label>Judul</label><input class="gt"></div><div class="field"><label>Gambar</label><input class="gf" type="file" accept="image/*"></div><div class="field"><label>Path</label><input class="gp"></div><button class="btn-admin danger remove-gallery">Hapus</button></div>`);bindGalleryRemove()};
function bindGalleryRemove(){document.querySelectorAll(".remove-gallery").forEach(b=>b.onclick=()=>b.parentElement.remove())}bindGalleryRemove();
$("#saveGallery").onclick=async()=>{try{const rows=[...document.querySelectorAll(".gallery-row")];for(const r of rows){const id=r.dataset.id;const file=r.querySelector(".gf").files[0];let path=r.querySelector(".gp").value.trim();if(file)path=await uploadPhoto(file);if(!path)continue;const payload={title:r.querySelector(".gt").value.trim()||"Family Moment",image_path:path,sort_order:rows.indexOf(r)};if(id)await sb.from("gallery").update(payload).eq("id",id);else await sb.from("gallery").insert(payload)}alert("Gallery tersimpan.");refresh()}catch(e){alert(e.message)}};
init();
